import type { Metadata } from "next";
import { Lato } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import { Navbar } from "@/components/Navbar";
import { Sidebar } from "@/components/Sidebar";
import Providers from "./providers";
import { AppLayout } from "./AppLayout";

const lato = Lato({
  variable: "--font-lato",
  subsets: ["latin"],
  weight: ["100", "300", "400", "700", "900"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Chat App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${lato.variable} antialiased`}>
        <div className="h-svh flex flex-col lg:flex-row overflow-hidden">
          <Navbar />
          <Providers>
            <Sidebar />
            <AppLayout>{children}</AppLayout>
          </Providers>
        </div>

        <Toaster />
      </body>
    </html>
  );
}
